version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app:/app/app
    environment:
      - DATABASE_URL=sqlite:///./glossary.db